name: Run Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false

      - name: Checkout LFS
        run: git lfs pull

      - uses: actions/setup-node@v4
        with:
          node-version-file: "project/.nvmrc"
          cache: "npm"
          cache-dependency-path: "project/package.json"

      - name: Install NPM Dependencies
        run: npm install
        working-directory: ./project

      - name: Run Tests
        run: npm run test
        working-directory: ./project
